Config = {}
Config.extractTime = 14000 -- seconds it takes to remove money from meter
Config.meterDistance = 1.0 -- distance from meter
Config.requiredCopsCount = 2 -- required cops count to start stealing
Config.policeCallInActionStart = true -- call police when player start stealing
Config.policeCallInActionEnd = true -- call police when player end stealing
Config.policeCallInActionFail = true -- call police when player fail stealing
Config.stealRequiredItem = "advancedlockpick" -- item required to start stealing
Config.parkMeterModels = {-1940238623, 2108567945} -- parkMeterModels in fivem
Config.MinMoneyWorth = 10 -- minimum money player can get from meter
Config.MaxMoneyWorth = 500 -- max money
Config.cooldownTimer = 60 * 60 * 1000 -- meter cooldown to be stolen again
Config.parkMeterRemoveOnSteal = false -- if false a marker will be shown in place
Config.parkMeterRemoveDistance = 50 -- distance to, show stolen marker, or remove meter entity
Config.RemoveRequiredItemChance = 50 -- remove item if fail, value between 1 and 100 (100 item will always be removed, 0 item will never be removed)
